#!/bin/sh

# vmware-user-suid-wrapper &
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &

setxkbmap us &
xset r rate 200 50 &
picom -b &
dwms &
# feh --no-fehbg --randomize --bg-scale $HOME/wall &
