#!/bin/bash

function MSGTXT()
{
    tput setaf 6
    echo $1
    tput sgr0
}

function CMDTXT()
{
    tput setaf 5
    echo $1
    tput sgr0
}

MSGTXT "[stow] (stow nvim using $HOME as target directory)"
stow nvim -t $HOME && CMDTXT "[stow] (symlink created, local)"

MSGTXT "[stow] (stow picom using $HOME as target directory)"
stow picom -t $HOME && CMDTXT "[stow] (symlink created, local)"

MSGTXT "[stow] (stow ranger using $HOME as target directory)"
stow ranger -t $HOME && CMDTXT "[stow] (symlink created, local)"

MSGTXT "[stow] (stow shell using $HOME as target directory)"
stow shell -t $HOME && CMDTXT "[stow] (symlink created, local)"

MSGTXT "[stow] (stow vifm using $HOME as target directory)"
stow vifm -t $HOME && CMDTXT "[stow] (symlink created, local)"

MSGTXT "[stow] (stow x11 using $HOME as target directory)"
stow x11 -t $HOME && CMDTXT "[stow] (symlink created, local)"

MSGTXT "[stow] (stow zathura using $HOME as target directory)"
stow zathura -t $HOME && CMDTXT "[stow] (symlink created, local)"

MSGTXT "[stow] (stow zsh using $HOME as target directory)"
stow zsh -t $HOME && CMDTXT "[stow] (symlink created, local)"

MSGTXT "[ln] (create symlink, profile)"
[ ! -L $HOME/.profile ] && ln -s $HOME/.config/shell/profile $HOME/.profile
CMDTXT "[ln] (symlink created, $HOME/.profile -> $HOME/.config/shell/profile)"

MSGTXT "[ln] (create symlink, zprofile)"
[ ! -L $HOME/.zprofile ] && ln -s $HOME/.config/shell/profile $HOME/.zprofile
CMDTXT "[ln] (symlink created, $HOME/.zprofile -> $HOME/.config/shell/profile)"

MSGTXT "[ln] (create symlink, xinitrc)"
[ ! -L $HOME/.xinitrc ] && ln -s $HOME/.config/x11/xinitrc $HOME/.xinitrc
CMDTXT "[ln] (symlink created, $HOME/.xinitrc -> $HOME/.config/x11/xinitrc)"

MSGTXT "[ln] (create symlink, xprofile)"
[ ! -L $HOME/.xprofile ] && ln -s $HOME/.config/x11/xprofile $HOME/.xprofile
CMDTXT "[ln] (symlink created, $HOME/.xprofile -> $HOME/.config/x11/xprofile)"
