#!/bin/bash

. /etc/os-release

case $ID in
    void)
        ./void_install
        ;;
    artix)
        ./artix_install
        ;;
esac

[ ! -L $HOME/.profile ] && ln -s $HOME/.config/shell/profile $HOME/.profile
[ ! -L $HOME/.zprofile ] && ln -s $HOME/.config/shell/profile $HOME/.zprofile
[ ! -L $HOME/.xinitrc ] && ln -s $HOME/.config/x11/xinitrc $HOME/.xinitrc
[ ! -L $HOME/.xprofile ] && ln -s $HOME/.config/x11/xprofile $HOME/.xprofile

stow local -t $HOME
stow nvim -t $HOME
stow picom -t $HOME
stow ranger -t $HOME
stow shell -t $HOME
stow vifm -t $HOME
stow x11 -t $HOME
stow zathura -t $HOME
stow zsh -t $HOME
