#!/bin/bash

. /etc/os-release
declare -a NF_TOOLS

if [[ $ID = "void" ]]; then
    declare -A R_TOOLS
    R_TOOLS["stow"]="stow"
    R_TOOLS["fd"]="fd"
    R_TOOLS["fzf"]="fzf"
    R_TOOLS["nvim"]="neovim"
    R_TOOLS["picom"]="picom"
    R_TOOLS["ranger"]="ranger"
    R_TOOLS["zathura"]="zathura"
    R_TOOLS["zathura"]="zathura-cb"
    R_TOOLS["zathura"]="zathura-djvu"
    R_TOOLS["zathura"]="zathura-pdf-mudpdf"
    R_TOOLS["zathura"]="zathura-ps"
    R_TOOLS["zsh"]="zsh"
    R_TOOLS["zsh"]="zsh-completions"
    R_TOOLS["exa"]="exa"
    R_TOOLS["rg"]="ripgrep"
    R_TOOLS["curl"]="curl"
    R_TOOLS["node"]="nodejs"
    R_TOOLS["wget"]="wget"
    R_TOOLS["gcc"]="gcc"
    R_TOOLS["gdb"]="gdb"
    R_TOOLS["clang"]="clang"
    R_TOOLS["clang"]="llvm"
    R_TOOLS["lldb"]="lldb"
    R_TOOLS["feh"]="feh"
    R_TOOLS["vifm"]="vifm"
    R_TOOLS["git"]="git"

    for R_TOOL in "${!R_TOOLS[@]}"
    do
        [[ ! -x "$(command -v $R_TOOL)" ]] && NF_TOOLS+=(${R_TOOLS[$R_TOOL]})
    done

    [[ ! -z $NF_TOOLS ]] && sudo xbps-install -Syv ${NF_TOOLS[*]}
fi

if [[ $ID = "artix" ]] || [[ $ID = "arch" ]]; then
    declare -A R_TOOLS
    R_TOOLS["stow"]="stow"
    R_TOOLS["fd"]="fd"
    R_TOOLS["fzf"]="fzf"
    R_TOOLS["nvim"]="neovim"
    R_TOOLS["picom"]="picom"
    R_TOOLS["ranger"]="ranger"
    R_TOOLS["zathura"]="zathura"
    R_TOOLS["zathura"]="zathura-cb"
    R_TOOLS["zathura"]="zathura-djvu"
    R_TOOLS["zathura"]="zathura-pdf-mudpdf"
    R_TOOLS["zathura"]="zathura-ps"
    R_TOOLS["zsh"]="zsh"
    R_TOOLS["zsh"]="zsh-completions"
    R_TOOLS["exa"]="exa"
    R_TOOLS["rg"]="ripgrep"
    R_TOOLS["curl"]="curl"
    R_TOOLS["node"]="nodejs"
    R_TOOLS["wget"]="wget"
    R_TOOLS["gcc"]="gcc"
    R_TOOLS["gdb"]="gdb"
    R_TOOLS["clang"]="clang"
    R_TOOLS["clang"]="llvm"
    R_TOOLS["lldb"]="lldb"
    R_TOOLS["feh"]="feh"
    R_TOOLS["vifm"]="vifm"
    R_TOOLS["git"]="git"

    for R_TOOL in "${!R_TOOLS[@]}"
    do
        [[ ! -x "$(command -v $R_TOOL)" ]] && NF_TOOLS+=(${R_TOOLS[$R_TOOL]})
    done

    [[ ! -z $NF_TOOLS ]] && sudo pacman -Syv ${NF_TOOLS[*]}
fi
