#!/bin/bash

declare -a NF_TOOLS
declare -A R_TOOLS

R_TOOLS["stow"]="stow"
R_TOOLS["fd"]="fd"
R_TOOLS["fzf"]="fzf"
R_TOOLS["nvim"]="neovim"
R_TOOLS["picom"]="picom"
R_TOOLS["ranger"]="ranger"
R_TOOLS["zathura"]="zathura zathura-cb zathura-djvu zathura-pdf-mupdf zathura-ps"
R_TOOLS["zsh"]="zsh zsh-completions"
R_TOOLS["exa"]="exa"
R_TOOLS["rg"]="ripgrep"
R_TOOLS["curl"]="curl"
R_TOOLS["node"]="nodejs"
R_TOOLS["wget"]="wget"
R_TOOLS["gcc"]="gcc"
R_TOOLS["gdb"]="gdb"
R_TOOLS["clang"]="clang llvm"
R_TOOLS["lldb"]="lldb"
R_TOOLS["feh"]="feh"
R_TOOLS["vifm"]="vifm"

for R_TOOL in "${!R_TOOLS[@]}"
do
    [[ ! -x "$(command -v $R_TOOL)" ]] && NF_TOOLS+=(${R_TOOLS[$R_TOOL]})
done

[[ ! -z $NF_TOOLS ]] && sudo xbps-install -Sy ${NF_TOOLS[*]}
