#!/bin/zsh

. /etc/os-release

# VOID
if [[ $ID = "void" ]]; then
    alias xu='sudo xbps-install -Suv'
    alias xh="sudo vpm"
    alias gu="xh up; xh cl; xh ar; vkl; vkr;"
    alias vkl="sudo vkpurge list"
    alias vkr="sudo vkpurge rm all"
    alias rh="sudo vsv"
    alias xi="xbps-query -Rs ''|cut -d' ' -f1-2|fzf -m --preview 'xbps-query -R {2}'|cut -d' ' -f2|xargs -ro sudo xbps-install -Sy"
    alias xp="xbps-query -Rs ''|cut -d' ' -f1-2|fzf -m --preview 'xbps-query -R {2}'|cut -d' ' -f2|xargs -ro sudo xbps-remove"
    alias xpp="xbps-query -Rs ''|cut -d' ' -f1-2|fzf -m --preview 'xbps-query -R {2}'|cut -d' ' -f2|xargs -ro sudo xbps-remove -R"
    
    [ -x "$(command -v nvim)" ] && \
        alias n='nvim' && \
        alias vim="nvim" && \
        alias vimdiff="nvim -d"
    [ -x "$(command -v vifm)" ] && alias e='vifm'
    [ -x "$(command -v exa)" ] && \
        alias f='exa -as type' \
        alias d='exa -aDT -L 1' \
        alias v='exa -lahg -s type' \
        alias t='exa -aT'
    [ -x "$(command -v fd)" ] && alias fd='fd -H -c always'
    [ -x "$(command -v neomutt)" ] && alias m='neomutt'
fi

# ARCH
if [[ $ID = "arch" ]]; then
    
    [ -x "$(command -v nvim)" ] && \
        alias n='nvim' && \
        alias vim="nvim" && \
        alias vimdiff="nvim -d"
    [ -x "$(command -v vifm)" ] && alias e='vifm'
    [ -x "$(command -v exa)" ] && \
        alias f='exa -as type' \
        alias d='exa -aDT -L 1' \
        alias v='exa -lahg -s type' \
        alias t='exa -aT'
    [ -x "$(command -v fd)" ] && alias fd='fd -H -c always'
    [ -x "$(command -v neomutt)" ] && alias m='neomutt'
fi

alias cs='clear'
alias shd='sudo shutdown -P now'
alias rbt='sudo shutdown -r now'
alias a='(&>/dev/null st -e zsh -c "cd $PWD; exec zsh" &)'
alias q='cd ..'
alias s="fzfed"
alias c="rangercd"
alias cp="cp -iv" 
alias mv="mv -iv" 
alias rm="rm -vI" 
alias mkd="mkdir -pv" 
alias wget="wget --no-hsts"
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
