#!/bin/zsh

os_release=$(awk -F '["=]+' '$1=="ID"{print $2}' /etc/os-release)
# os_release=$(sed -nE 's/^ID="([^"]+)".*/\1/p' /etc/os-release)
# os_release=$(grep -oP '^ID="\K[^"]+' /etc/os-release)

# VOID
if [[ $os_release = "void" ]]; then
    alias xu='sudo xbps-install -Suv'
    alias xh="sudo vpm"
    alias gu="xh up; xh cl; xh ar; vkl; vkr;"
    alias vkl="sudo vkpurge list"
    alias vkr="sudo vkpurge rm all"
    
    [ -x "$(command -v nvim)" ] && \
        alias n='nvim' && \
        alias vim="nvim" && \
        alias vimdiff="nvim -d"
    [ -x "$(command -v vifm)" ] && alias e='vifm'
    [ -x "$(command -v exa)" ] && \
        alias f='exa -as type' \
        alias d='exa -aDT -L 1' \
        alias v='exa -lahg -s type' \
        alias t='exa -aT'
    [ -x "$(command -v fd)" ] && alias fd='fd -H -c always'
fi

# ARTIX
if [[ $os_release = "artix" ]]; then
    
    [ -x "$(command -v nvim)" ] && \
        alias n='nvim' && \
        alias vim="nvim" && \
        alias vimdiff="nvim -d"
    [ -x "$(command -v vifm)" ] && alias e='vifm'
    [ -x "$(command -v exa)" ] && \
        alias f='exa -as type' \
        alias d='exa -aDT -L 1' \
        alias v='exa -lahg -s type' \
        alias t='exa -aT'
    [ -x "$(command -v fd)" ] && alias fd='fd -H -c always'
fi

# alias m='glances'

alias shd='sudo shutdown -P now'
alias rbt='sudo shutdown -r now'
alias q='cd ..'
alias s="fzfed"
alias c="ranger-cd"
alias cp="cp -iv" 
alias mv="mv -iv" 
alias rm="rm -vI" 
alias mkd="mkdir -pv" 
alias wget="wget --no-hsts"
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

# alias f='lsd -A --icon never'
# alias v='lsd -lA --group-dirs first --icon never'
# alias i4="ip -oneline -4 addr show INTERFACE|awk '{print \$4}'|cut -d/ -f1"
