#!/bin/zsh

typeset -U PATH path
path=("$HOME/.local/bin" "$HOME/.cargo/bin" "$path[@]")
export PATH

export EDITOR="nvim"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export LESSHISTFILE="-"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
